@contributor{Vadim Zaytsev - vadim@grammarware.net - UvA}
module meta::Mutations

import IO;
import String;
import grammarlab::lib::Sizes;

void main()
{
	// massage
	int cx = 0;
	str buf = "@contributor{Vadim Zaytsev - vadim@grammarware.net - UvA}
	'@contributor{Generated by meta::Mutations, do not edit manually!}
	'@doc{Contains $$CX$$ mutations intentionally generalised from massage-equivalence.}
	'module grammarlab::transform::sleir::Massage
	'
	'import grammarlab::language::Grammar;
	'import grammarlab::language::SLEIR;
	'";
	for(
		str line <- readFileLines(|project://grammarlab/src/grammarlab/transform/XBGF.rsc|),
		/bool massage_eq\(\{<zet:[^}]+>\}\) = true; \/\/@<left:[^-]+>-<right:.*>$/ := line
	)
	{
		pair = split(", ",zet);
		if (isEmpty(right))
		{
			f = ""; t = "";
			if (contains(pair[0],"_") && !contains(pair[1],"_")) {f = pair[0]; t = pair[1];}
			elseif (!contains(pair[0],"_") && contains(pair[1],"_")) {f = pair[1]; t = pair[0];}
			else {buf += "//ERROR: <pair[0]> =\> <pair[1]>";continue;}
			buf += function("massage","Massage<left>",f,t);
			cx += 1;
		} 
		else
		{
			buf += function("massage","Massage<left>2<right>",pair[0],pair[1]);
			buf += function("massage","Massage<right>2<left>",pair[1],pair[0]);
			cx += 2;
		}
	}
	writeFile(|project://grammarlab/src/grammarlab/transform/sleir/Massage.rsc|,replaceAll(buf,"$$CX$$","<cx>"));
	// narrow and widen
	//bool narrowing( star(e), plus(e) ) = true; //#Star-Plus
	cx = 0;
	buf = "@contributor{Vadim Zaytsev - vadim@grammarware.net - UvA}
	'@contributor{Generated by meta::Mutations, do not edit manually!}
	'@doc{Contains $$CX$$ mutations intentionally generalised from narrow-/widen-equivalence.}
	'module grammarlab::transform::sleir::Width
	'
	'import grammarlab::language::Grammar;
	'import grammarlab::language::SLEIR;
	'";
	for(
		str line <- readFileLines(|project://grammarlab/src/grammarlab/transform/XBGF.rsc|),
		//contains(" //#",line),
		/bool narrowing\( <from:[^ ]+>, <to:[^ ]+> \) = true; \/\/#<left:[^-]+>-<right:.*>$/ := line
	)
	{
		if (from != "e")
			{buf += function("narrow","Narrow<left>2<right>",from,to);cx+=1;}
		if (to != "e")
			{buf += function("widen","Widen<right>2<left>",to,from);cx+=1;}
	}
	writeFile(|project://grammarlab/src/grammarlab/transform/sleir/Width.rsc|,replaceAll(buf,"$$CX$$","<cx>"));}

str function(str base, str name, str from, str to) =
	"
	'// SLEIR:<name>
	'@doc{<base> ⊢ <name>, Type III, page 9}
	'public GGrammar mutate(<name>(), GGrammar g)
	'{
	'	g.P = visit(g.P){case <from> =\> <to>};
	'	return g;
	'}";
