@contributor{Vadim Zaytsev - vadim@grammarware.net - SWAT, CWI}
@contributor{Generated by meta::Glue, do not edit manually!}
module grammarlab::language::glue::Mutations

import grammarlab::language::glue::Productions;

lexical GlueKAbridgeAll = @category="MetaAmbiguity" "AbridgeAll";
lexical GlueKDeyaccifyAll = @category="MetaAmbiguity" "DeyaccifyAll";
lexical GlueKDistributeAll = @category="MetaAmbiguity" "DistributeAll";
lexical GlueKEliminateTop = @category="MetaAmbiguity" "EliminateTop";
lexical GlueKEquateAll = @category="MetaAmbiguity" "EquateAll";
lexical GlueKFoldMax = @category="MetaAmbiguity" "FoldMax";
lexical GlueKHorizontalAll = @category="MetaAmbiguity" "HorizontalAll";
lexical GlueKInlineMax = @category="MetaAmbiguity" "InlineMax";
lexical GlueKInlinePlus = @category="MetaAmbiguity" "InlinePlus";
lexical GlueKLiftTopLabels = @category="MetaAmbiguity" "LiftTopLabels";
lexical GlueKUnchainAll = @category="MetaAmbiguity" "UnchainAll";
lexical GlueKUnfoldMax = @category="MetaAmbiguity" "UnfoldMax";
lexical GlueKVerticalAll = @category="MetaAmbiguity" "VerticalAll";

keyword GlueKw = GlueKAbridgeAll | GlueKDeyaccifyAll | GlueKDistributeAll | GlueKEliminateTop | GlueKEquateAll | GlueKFoldMax | GlueKHorizontalAll | GlueKInlineMax | GlueKInlinePlus | GlueKLiftTopLabels | GlueKUnchainAll | GlueKUnfoldMax | GlueKVerticalAll;

syntax GlueCommand
	= GlueKAbridgeAll "."
	| GlueKDeyaccifyAll "."
	| GlueKDistributeAll "."
	| GlueKEliminateTop "."
	| GlueKEquateAll "."
	| GlueKFoldMax "."
	| GlueKHorizontalAll "."
	| GlueKInlineMax "."
	| GlueKInlinePlus "."
	| GlueKLiftTopLabels "."
	| GlueKUnchainAll "."
	| GlueKUnfoldMax "."
	| GlueKVerticalAll "."
	;