@contributor{Vadim Zaytsev - vadim@grammarware.net - SWAT, CWI}
@contributor{Generated by meta::Glue, do not edit manually!}
module grammarlab::language::GET

data GExternalType
	= GETrscd()
	| GETrscs()
	| GETrscf()
	| GETsdf()
	| GETbgf()
	| GETrng()
	| GETxsd()
	| GETpgf()
	;
